# NumPy 学习指南

## 目录
1. [NumPy简介](#1-numpy简介)
2. [数组创建](#2-数组创建)
3. [数组属性](#3-数组属性)
4. [数组索引和切片](#4-数组索引和切片)
5. [数组形状操作](#5-数组形状操作)
6. [数组拼接与分割](#6-数组拼接与分割)
7. [数学运算](#7-数学运算)
8. [统计函数](#8-统计函数)
9. [线性代数](#9-线性代数)
10. [随机数生成](#10-随机数生成)
11. [实践练习](#11-实践练习)


## 1. NumPy简介

NumPy（Numerical Python）是Python中用于科学计算的基础库，提供了高性能的多维数组对象和用于处理这些数组的工具。

### 主要特点：
- **高性能**：使用C语言实现，运算速度快
- **多维数组**：支持N维数组（ndarray）
- **丰富的函数库**：数学、统计、线性代数等
- **广播机制**：自动处理不同形状数组的运算
- **内存效率**：连续内存存储，访问效率高


In [1]:
import numpy as np

## 2. 数组创建

NumPy提供了多种创建数组的方法，从列表转换、特殊数组生成到从文件读取等。


In [2]:
# 方法1：从Python列表创建数组
arr1 = np.array([1, 2, 3, 4, 5])
print("从列表创建一维数组:", arr1)

从列表创建一维数组: [1 2 3 4 5]


In [3]:
# 从嵌套列表创建二维数组
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n从嵌套列表创建二维数组:")
print(arr2)


从嵌套列表创建二维数组:
[[1 2 3]
 [4 5 6]]


In [4]:
# 方法2：创建全零数组
zeros = np.zeros((3, 4))  # 创建3行4列的全零数组
print("全零数组:")
print(zeros)


全零数组:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# 方法3：创建全1数组
ones = np.ones((2, 3))  # 创建2行3列的全1数组
print("全1数组:")
print(ones)


全1数组:
[[1. 1. 1.]
 [1. 1. 1.]]


### ⭐ 重点复习：方法4 - np.full() 创建指定值数组

**功能说明：**
- `np.full()` 用于创建指定形状的数组，所有元素都填充为同一个值
- 与 `np.zeros()` 和 `np.ones()` 类似，但可以指定任意填充值

**语法：** `np.full(shape, fill_value, dtype=None)`
- `shape`: 数组的形状（元组形式，如 (2, 3) 表示2行3列）
- `fill_value`: 要填充的值（可以是数字、字符串等）
- `dtype`: 可选，指定数据类型

**应用场景：**
- 初始化数组为特定值（如初始化为7、-1等）
- 创建常量数组
- 在某些算法中需要特定初始值


In [ ]:
# 方法4：创建指定值的数组
# np.full(shape, fill_value) - 创建指定形状，所有元素都是fill_value的数组
full = np.full((2, 2), 7)  # 创建2x2的数组，所有元素都是7
print("指定值数组:")
print(full)


指定值数组:
[[7 7]
 [7 7]]


### ⭐ 重点复习：方法5 - np.eye() 创建单位矩阵

**功能说明：**
- `np.eye()` 用于创建单位矩阵（Identity Matrix）
- 单位矩阵是方阵（行数=列数），主对角线元素为1，其他元素为0
- 在矩阵运算中，单位矩阵类似于数字1的作用（任何矩阵乘以单位矩阵等于自身）

**语法：** `np.eye(N, M=None, k=0, dtype=float)`
- `N`: 行数（必需）
- `M`: 列数（可选，默认等于N，创建方阵）
- `k`: 对角线的索引（默认0表示主对角线，正数表示上对角线，负数表示下对角线）
- `dtype`: 数据类型（默认float）

**应用场景：**
- 线性代数运算（矩阵乘法中的单位元）
- 初始化神经网络权重矩阵
- 矩阵求逆等数学运算


In [7]:
# 方法5：创建单位矩阵（对角线为1，其他为0）
# np.eye(N) - 创建N×N的单位矩阵
identity = np.eye(3)  # 创建3x3单位矩阵
print("单位矩阵:")
print(identity)

# 详细解释：
# - np.eye(3) 创建了一个3行3列的单位矩阵
# - 主对角线（从左上到右下）的元素都是1
# - 其他位置的元素都是0
# - 结果：[[1, 0, 0], [0, 1, 0], [0, 0, 1]]
# 
# 单位矩阵的特性：
# - 任何矩阵A乘以单位矩阵I，结果还是A：A × I = A
# - 单位矩阵乘以自身还是单位矩阵：I × I = I
# - 单位矩阵的逆矩阵就是它本身：I^(-1) = I
# 
# 示例：验证单位矩阵的特性
# A = np.array([[1, 2], [3, 4]])
# I = np.eye(2)
# print(A @ I)  # 结果还是 [[1, 2], [3, 4]]


单位矩阵:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# 方法6：创建等差数列数组
arange = np.arange(0, 10, 2)  # 从0到10（不含），步长为2
print("等差数列 (arange):", arange)


等差数列 (arange): [0 2 4 6 8]


In [9]:
# 方法7：创建等间距数组
linspace = np.linspace(0, 1, 5)  # 从0到1，均匀分成5个点
print("等间距数组 (linspace):", linspace)


等间距数组 (linspace): [0.   0.25 0.5  0.75 1.  ]


In [10]:
# 方法8：创建随机数组
random_arr = np.random.rand(3, 3)  # 创建3x3的随机数组（0-1之间）
print("随机数组:")
print(random_arr)


随机数组:
[[0.75317059 0.30954305 0.68951416]
 [0.14552273 0.60776004 0.9140391 ]
 [0.26690619 0.1045854  0.22282799]]


## 3. 数组属性

了解数组的属性对于操作数组非常重要，包括形状、维度、数据类型等。


### ⭐ 重点复习：数组内存属性 - itemsize 和 nbytes

**itemsize（元素字节数）说明：**
- `itemsize` 返回数组中**每个元素**占用的字节数
- 不同数据类型占用的字节数不同：
  - `int8`: 1字节
  - `int16`: 2字节
  - `int32`: 4字节
  - `int64`: 8字节
  - `float32`: 4字节
  - `float64`: 8字节

**nbytes（总字节数）说明：**
- `nbytes` 返回数组**总共**占用的内存字节数
- 计算公式：`nbytes = size × itemsize`
  - `size`: 数组中元素的总数
  - `itemsize`: 每个元素的字节数

**实际应用：**
- 内存优化：了解数组占用内存大小，优化程序性能
- 数据类型选择：根据精度需求选择合适的数据类型（如float32 vs float64）
- 大数据处理：估算大型数组的内存需求

**示例计算：**
- 数组形状 (3, 4) = 12个元素
- 如果 dtype=int64，itemsize=8字节
- 总字节数 nbytes = 12 × 8 = 96字节


In [ ]:
# 创建一个示例数组
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("数组内容:")
print(arr)
# 数组形状 (shape) - 返回一个元组，表示各维度的大小
print(f"\n数组形状 (shape): {arr.shape}")  # (3, 4) 表示3行4列

# 数组维度 (ndim) - 返回数组的维度数
print(f"数组维度 (ndim): {arr.ndim}")  # 2维

# 数组大小 (size) - 返回数组中元素的总数
print(f"数组大小 (size): {arr.size}")  # 12个元素

# 数据类型 (dtype) - 返回数组中元素的数据类型
print(f"数据类型 (dtype): {arr.dtype}")  # int32或int64

# 每个元素占用的字节数 (itemsize)
# itemsize 表示数组中每个元素占用的内存字节数
# 不同数据类型的itemsize：
# - int8: 1字节, int16: 2字节, int32: 4字节, int64: 8字节
# - float32: 4字节, float64: 8字节
print(f"元素字节数 (itemsize): {arr.itemsize}")  # 根据dtype决定，int64为8字节

# 数组总字节数 (nbytes)
# nbytes = size × itemsize
# 表示整个数组占用的总内存大小
# 例如：12个元素 × 8字节/元素 = 96字节
print(f"总字节数 (nbytes): {arr.nbytes}")  # 总内存占用
print(f"验证计算: size({arr.size}) × itemsize({arr.itemsize}) = {arr.size * arr.itemsize}")

# 修改数据类型
arr_float = arr.astype(np.float64)  # 转换为浮点型
print(f"\n转换为浮点型后的数据类型: {arr_float.dtype}")



数组内容:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

数组形状 (shape): (3, 4)
数组维度 (ndim): 2
数组大小 (size): 12
数据类型 (dtype): int64
元素字节数 (itemsize): 8
总字节数 (nbytes): 96

转换为浮点型后的数据类型: float64


## 4. 数组索引和切片

NumPy的索引和切片功能非常强大，可以高效地访问和修改数组元素。


In [ ]:
# 创建示例数组
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("原始数组:")
print(arr)

# 一维数组索引
arr1d = np.array([10, 20, 30, 40, 50])
print(f"\n一维数组: {arr1d}")
print(f"第一个元素: {arr1d[0]}")  # 索引从0开始
print(f"最后一个元素: {arr1d[-1]}")  # 负数索引从末尾开始
print(f"前三个元素: {arr1d[0:3]}")  # 切片 [起始:结束)，不包含结束位置

# 二维数组索引
print(f"\n二维数组索引:")
print(f"第一行: {arr[0]}")  # 获取第一行
print(f"第一行第二列的元素: {arr[0, 1]}")  # 获取第0行第1列的元素
print(f"第二列: {arr[:, 1]}")  # 获取所有行的第1列

# 数组切片
print(f"\n数组切片:")
print(f"前两行: \n{arr[0:2]}")  # 获取前两行
print(f"前两行，前两列: \n{arr[0:2, 0:2]}")  # 获取前两行前两列的子数组

# 布尔索引 - 根据条件选择元素
print(f"\n布尔索引:")
mask = arr > 5  # 创建布尔掩码
print(f"大于5的元素: {arr[mask]}")  # 返回所有大于5的元素

# 花式索引 (Fancy Indexing) - 使用整数数组索引
print(f"\n花式索引:")
indices = [0, 2]  # 选择第0行和第2行
print(f"选择第0行和第2行: \n{arr[indices]}")
print(f"选择第0列和第2列: \n{arr[:, [0, 2]]}")


## 5. 数组形状操作

改变数组的形状是NumPy中常见的操作，包括重塑、展平、转置等。


In [ ]:
# 创建示例数组
arr = np.arange(12)  # [0, 1, 2, ..., 11]
print(f"原始一维数组: {arr}")
# reshape - 重塑数组形状（不改变原数组，返回新数组）
arr_2d = arr.reshape(3, 4)  # 重塑为3行4列
print(f"\n重塑为3x4数组:")
print(arr_2d)

# 注意：reshape的总元素数必须等于原数组
# arr.reshape(3, 5)  # 这会报错，因为3*5=15 != 12

# flatten 或 ravel - 将多维数组展平为一维
arr_flat = arr_2d.flatten()  # 返回展平后的数组（新数组）
print(f"\n展平后的数组: {arr_flat}")

arr_ravel = arr_2d.ravel()  # 返回展平后的数组视图（如果可能）
print(f"ravel展平: {arr_ravel}")

# 转置 (transpose 或 T)
arr_transpose = arr_2d.T  # 或使用 arr_2d.transpose()
print(f"\n转置后的数组:")
print(arr_transpose)

# resize - 改变数组大小（会修改原数组或返回新数组）
arr_resize = np.array([1, 2, 3, 4, 5])
arr_resize.resize(3, 3)  # 如果新大小更大，会用0填充
print(f"\nresize后的数组:")
print(arr_resize)

# 增加维度
arr_1d = np.array([1, 2, 3])
arr_2d_new = arr_1d[:, np.newaxis]  # 在列方向增加维度
print(f"\n增加维度:")
print(f"原始: {arr_1d}, shape: {arr_1d.shape}")
print(f"增加维度后: \n{arr_2d_new}, shape: {arr_2d_new.shape}")



## 6. 数组拼接与分割

NumPy提供了多种方法来拼接和分割数组，这对于数据重组非常有用。


In [ ]:
# 创建示例数组
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("数组1:")
print(arr1)
print("\n数组2:")
print(arr2)
# concatenate - 沿指定轴拼接数组
arr_concat = np.concatenate([arr1, arr2], axis=0)  # 沿行方向（垂直）拼接
print("\n垂直拼接 (axis=0):")
print(arr_concat)

arr_concat2 = np.concatenate([arr1, arr2], axis=1)  # 沿列方向（水平）拼接
print("\n水平拼接 (axis=1):")
print(arr_concat2)

# vstack - 垂直堆叠（沿行方向）
arr_vstack = np.vstack([arr1, arr2])
print("\n垂直堆叠 (vstack):")
print(arr_vstack)

# hstack - 水平堆叠（沿列方向）
arr_hstack = np.hstack([arr1, arr2])
print("\n水平堆叠 (hstack):")
print(arr_hstack)

# 数组分割
arr = np.arange(12).reshape(3, 4)
print(f"\n原始数组:")
print(arr)

# split - 分割数组
arrs = np.split(arr, 3, axis=0)  # 沿行方向分割成3份
print("\n沿行方向分割成3份:")
for i, a in enumerate(arrs):
    print(f"第{i+1}份:")
    print(a)

# vsplit - 垂直分割
arrs_v = np.vsplit(arr, 3)  # 垂直分割成3份
print("\n垂直分割:")
for i, a in enumerate(arrs_v):
    print(f"第{i+1}份:")
    print(a)

# hsplit - 水平分割
arrs_h = np.hsplit(arr, 2)  # 水平分割成2份
print("\n水平分割:")
for i, a in enumerate(arrs_h):
    print(f"第{i+1}份:")
    print(a)



## 7. 数学运算

NumPy提供了丰富的数学运算功能，支持元素级运算和数组级运算。


In [ ]:
# 创建示例数组
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
# 基本算术运算（元素级运算）
print("数组a:", a)
print("数组b:", b)
print(f"\n加法 (a + b): {a + b}")  # [6, 8, 10, 12]
print(f"减法 (a - b): {a - b}")  # [-4, -4, -4, -4]
print(f"乘法 (a * b): {a * b}")  # [5, 12, 21, 32]（元素级，不是矩阵乘法）
print(f"除法 (b / a): {b / a}")  # [5.0, 3.0, 2.33..., 2.0]
print(f"幂运算 (a ** 2): {a ** 2}")  # [1, 4, 9, 16]

# 标量与数组运算（广播机制）
print(f"\n标量运算:")
print(f"a + 10: {a + 10}")  # 每个元素加10
print(f"a * 2: {a * 2}")  # 每个元素乘以2

# 矩阵乘法
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix_a, matrix_b)  # 或使用 matrix_a @ matrix_b
print(f"\n矩阵乘法:")
print(f"矩阵A:\n{matrix_a}")
print(f"矩阵B:\n{matrix_b}")
print(f"矩阵乘积:\n{matrix_product}")

# 数学函数
arr = np.array([1, 4, 9, 16, 25])
print(f"\n数学函数:")
print(f"数组: {arr}")
print(f"平方根: {np.sqrt(arr)}")
print(f"指数: {np.exp([1, 2, 3])}")  # e的幂次
print(f"对数: {np.log([1, 2, 3, 4])}")  # 自然对数
print(f"正弦值: {np.sin([0, np.pi/2, np.pi])}")

# 三角函数
angles = np.array([0, np.pi/4, np.pi/2])
print(f"\n三角函数:")
print(f"角度: {angles}")
print(f"sin: {np.sin(angles)}")
print(f"cos: {np.cos(angles)}")
print(f"tan: {np.tan(angles)}")



## 8. 统计函数

NumPy提供了丰富的统计函数，用于计算数组的统计信息。


In [ ]:
# 创建示例数组
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("数组:")
print(arr)
# 基本统计函数
print(f"\n基本统计:")
print(f"最小值 (min): {np.min(arr)}")  # 整个数组的最小值
print(f"最大值 (max): {np.max(arr)}")  # 整个数组的最大值
print(f"平均值 (mean): {np.mean(arr)}")  # 整个数组的平均值
print(f"中位数 (median): {np.median(arr)}")  # 中位数
print(f"标准差 (std): {np.std(arr):.2f}")  # 标准差
print(f"方差 (var): {np.var(arr):.2f}")  # 方差
print(f"总和 (sum): {np.sum(arr)}")  # 所有元素的和
print(f"乘积 (prod): {np.prod(arr)}")  # 所有元素的乘积

# 沿轴统计（指定维度）
print(f"\n沿轴统计:")
print(f"每行的平均值 (axis=1): {np.mean(arr, axis=1)}")  # 沿行方向（每行）
print(f"每列的平均值 (axis=0): {np.mean(arr, axis=0)}")  # 沿列方向（每列）
print(f"每行的最大值: {np.max(arr, axis=1)}")
print(f"每列的最小值: {np.min(arr, axis=0)}")

# 累积函数
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"\n累积函数:")
print(f"数组: {arr_1d}")
print(f"累积和 (cumsum): {np.cumsum(arr_1d)}")  # [1, 3, 6, 10, 15]
print(f"累积积 (cumprod): {np.cumprod(arr_1d)}")  # [1, 2, 6, 24, 120]

# 排序
arr_unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print(f"\n排序:")
print(f"原数组: {arr_unsorted}")
print(f"排序后: {np.sort(arr_unsorted)}")  # 返回排序后的新数组
print(f"排序索引: {np.argsort(arr_unsorted)}")  # 返回排序后的索引

# 唯一值
arr_duplicate = np.array([1, 2, 2, 3, 3, 3, 4])
print(f"\n唯一值:")
print(f"原数组: {arr_duplicate}")
print(f"唯一值: {np.unique(arr_duplicate)}")  # 返回唯一值并排序
print(f"唯一值计数: {np.bincount(arr_duplicate)}")  # 计数每个值的出现次数



## 9. 线性代数

NumPy的线性代数模块（linalg）提供了丰富的线性代数运算功能。


In [ ]:
# 创建示例矩阵
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("矩阵A:")
print(A)
print("\n矩阵B:")
print(B)
# 矩阵乘法
product = np.dot(A, B)  # 或使用 A @ B
print("\n矩阵乘积 (A @ B):")
print(product)

# 矩阵转置
print("\n矩阵A的转置:")
print(A.T)

# 矩阵的迹（对角线元素之和）
trace = np.trace(A)
print(f"\n矩阵A的迹: {trace}")

# 矩阵的行列式
det = np.linalg.det(A)
print(f"矩阵A的行列式: {det:.2f}")

# 矩阵的逆
A_inv = np.linalg.inv(A)
print("\n矩阵A的逆:")
print(A_inv)

# 验证：A @ A_inv 应该等于单位矩阵
identity_check = A @ A_inv
print("\n验证 (A @ A_inv，应该接近单位矩阵):")
print(identity_check)

# 特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\n特征值:")
print(eigenvalues)
print("\n特征向量:")
print(eigenvectors)

# 矩阵的秩
rank = np.linalg.matrix_rank(A)
print(f"\n矩阵A的秩: {rank}")

# 求解线性方程组 Ax = b
b = np.array([5, 11])
x = np.linalg.solve(A, b)  # 求解 Ax = b
print(f"\n求解线性方程组 Ax = b:")
print(f"b = {b}")
print(f"解 x = {x}")
print(f"验证: A @ x = {A @ x}")  # 应该等于b



## 10. 随机数生成

NumPy的random模块提供了丰富的随机数生成功能，这对于模拟和采样非常有用。


In [ ]:
# 设置随机种子（用于可重复性）
np.random.seed(42)



In [ ]:
# 生成随机浮点数（0到1之间）
random_float = np.random.rand(3, 3)  # 生成3x3的随机数组
print("随机浮点数数组 (0-1):")
print(random_float)


In [ ]:
# 生成随机整数
random_int = np.random.randint(1, 10, size=(3, 3))  # 生成1到9之间的随机整数
print("随机整数数组 (1-9):")
print(random_int)


In [ ]:
# 从指定数组中选择随机元素
choices = np.random.choice([1, 2, 3, 4, 5], size=10)  # 从数组中随机选择10个元素
print("从数组中随机选择:", choices)


In [ ]:
# 正态分布随机数
normal = np.random.normal(loc=0, scale=1, size=1000)  # 均值0，标准差1
print("正态分布随机数:")
print(f"均值: {np.mean(normal):.2f}")
print(f"标准差: {np.std(normal):.2f}")


In [ ]:
# 均匀分布随机数
uniform = np.random.uniform(low=0, high=10, size=100)  # 0到10之间的均匀分布
print("均匀分布随机数 (0-10):")
print(f"最小值: {np.min(uniform):.2f}, 最大值: {np.max(uniform):.2f}")


In [ ]:
# 随机打乱数组
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.random.shuffle(arr)  # 原地打乱
print("打乱后的数组:", arr)


In [ ]:
# 随机排列
permutation = np.random.permutation([1, 2, 3, 4, 5])  # 返回打乱后的新数组
print("随机排列:", permutation)


In [ ]:
# 二项分布
binomial = np.random.binomial(n=10, p=0.5, size=100)  # 10次试验，成功概率0.5
print("二项分布 (n=10, p=0.5):")
print(f"前10个值: {binomial[:10]}")


## 11. 实践练习

通过以下练习来巩固NumPy的使用。


### 练习1：创建和操作数组

创建一个5x5的数组，其中：
- 对角线元素为1
- 其他元素为0
- 然后将第2行和第4行交换


In [ ]:
# 练习1解答
# 创建5x5单位矩阵
arr = np.eye(5)
print("原始数组（单位矩阵）:")
print(arr)

# 交换第2行（索引1）和第4行（索引3）
arr[[1, 3]] = arr[[3, 1]]  # 使用花式索引交换行
print("\n交换第2行和第4行后:")
print(arr)


### 练习2：数组统计

给定一个包含学生成绩的数组，计算：
- 每个学生的平均分
- 每门课的平均分
- 所有成绩的平均分、最高分、最低分


In [ ]:
# 练习2解答
# 创建学生成绩数组（5个学生，3门课程）
scores = np.array([
    [85, 90, 88],
    [78, 82, 80],
    [92, 88, 90],
    [75, 80, 78],
    [88, 85, 87]
])

print("学生成绩数组:")
print(scores)
print(f"形状: {scores.shape} (5个学生，3门课程)")

# 每个学生的平均分（沿列方向求平均，axis=1）
student_avg = np.mean(scores, axis=1)
print(f"\n每个学生的平均分: {student_avg}")

# 每门课的平均分（沿行方向求平均，axis=0）
course_avg = np.mean(scores, axis=0)
print(f"每门课的平均分: {course_avg}")

# 所有成绩的统计
print(f"\n所有成绩统计:")
print(f"平均分: {np.mean(scores):.2f}")
print(f"最高分: {np.max(scores)}")
print(f"最低分: {np.min(scores)}")
print(f"标准差: {np.std(scores):.2f}")


### 练习3：数组过滤和条件操作

从一个数组中筛选出满足条件的元素，并进行相应的操作。


In [ ]:
# 练习3解答
# 创建一个包含随机数的数组
np.random.seed(42)
arr = np.random.randint(0, 100, size=20)
print("原始数组:")
print(arr)

# 筛选出大于50的元素
filtered = arr[arr > 50]
print(f"\n大于50的元素: {filtered}")

# 将小于30的元素替换为0
arr_modified = arr.copy()  # 复制数组，避免修改原数组
arr_modified[arr_modified < 30] = 0
print(f"\n将小于30的元素替换为0:")
print(arr_modified)

# 使用多个条件
condition = (arr > 30) & (arr < 70)  # 大于30且小于70
filtered_range = arr[condition]
print(f"\n大于30且小于70的元素: {filtered_range}")

# 使用where函数进行条件替换
arr_where = np.where(arr > 50, arr, -1)  # 大于50保持原值，否则替换为-1
print(f"\n使用where函数（大于50保持，否则为-1）:")
print(arr_where)


### 练习4：矩阵运算

实现两个矩阵的运算，包括矩阵乘法、转置等。


In [ ]:
# 练习4解答
# 创建两个矩阵
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

print("矩阵A (2x3):")
print(A)
print("\n矩阵B (3x2):")
print(B)

# 矩阵乘法 A @ B (2x3 @ 3x2 = 2x2)
C = A @ B
print("\n矩阵乘积 A @ B (2x2):")
print(C)

# 矩阵转置
A_T = A.T
print("\n矩阵A的转置 (3x2):")
print(A_T)

# 计算 (A @ B) 的转置，应该等于 B^T @ A^T
C_T = C.T
B_T_A_T = B.T @ A.T
print("\n验证转置性质:")
print(f"(A @ B)^T:\n{C_T}")
print(f"B^T @ A^T:\n{B_T_A_T}")
print(f"是否相等: {np.allclose(C_T, B_T_A_T)}")  # 使用allclose比较浮点数


### 练习5：数组重塑和广播

理解数组的广播机制，并完成数组形状的转换。


In [ ]:
# 练习5解答
# 广播机制示例
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_1d = np.array([10, 20, 30])

print("二维数组:")
print(arr_2d)
print("\n一维数组:")
print(arr_1d)

# 广播：一维数组会自动扩展以匹配二维数组的形状
result = arr_2d + arr_1d  # 每行都加上arr_1d
print("\n广播加法结果（每行加上一维数组）:")
print(result)

# 重塑数组
arr_flat = np.arange(24)
print(f"\n原始一维数组（24个元素）: {arr_flat}")

# 重塑为不同的形状
arr_2x12 = arr_flat.reshape(2, 12)
arr_3x8 = arr_flat.reshape(3, 8)
arr_4x6 = arr_flat.reshape(4, 6)
arr_2x3x4 = arr_flat.reshape(2, 3, 4)  # 三维数组

print("\n重塑为不同形状:")
print(f"2x12: shape = {arr_2x12.shape}")
print(f"3x8: shape = {arr_3x8.shape}")
print(f"4x6: shape = {arr_4x6.shape}")
print(f"2x3x4: shape = {arr_2x3x4.shape}")

# 使用-1自动计算维度
arr_auto = arr_flat.reshape(4, -1)  # -1表示自动计算
print(f"\n使用-1自动计算: reshape(4, -1) -> shape = {arr_auto.shape}")


### 练习6：综合应用 - 数据分析

模拟一个简单的数据分析场景，使用NumPy进行数据处理。


In [ ]:
# 练习6解答：综合应用
# 模拟销售数据：4个产品，12个月的数据
np.random.seed(42)
sales_data = np.random.randint(100, 1000, size=(4, 12))
products = ['产品A', '产品B', '产品C', '产品D']
months = ['1月', '2月', '3月', '4月', '5月', '6月', 
          '7月', '8月', '9月', '10月', '11月', '12月']

print("销售数据（4个产品 x 12个月）:")
print(sales_data)

# 1. 每个产品的年度总销售额
product_totals = np.sum(sales_data, axis=1)
print("\n每个产品的年度总销售额:")
for i, total in enumerate(product_totals):
    print(f"{products[i]}: {total}")

# 2. 每个月的总销售额
month_totals = np.sum(sales_data, axis=0)
print("\n每个月的总销售额:")
for i, total in enumerate(month_totals):
    print(f"{months[i]}: {total}")

# 3. 找出销售额最高的产品和月份
max_product_idx = np.argmax(product_totals)
max_month_idx = np.argmax(month_totals)
print(f"\n销售额最高的产品: {products[max_product_idx]} ({product_totals[max_product_idx]})")
print(f"销售额最高的月份: {months[max_month_idx]} ({month_totals[max_month_idx]})")

# 4. 计算每个产品的平均月销售额
product_avg = np.mean(sales_data, axis=1)
print("\n每个产品的平均月销售额:")
for i, avg in enumerate(product_avg):
    print(f"{products[i]}: {avg:.2f}")

# 5. 找出销售额超过800的月份和产品
high_sales = sales_data > 800
print("\n销售额超过800的记录:")
for i in range(4):
    for j in range(12):
        if high_sales[i, j]:
            print(f"{products[i]} 在 {months[j]}: {sales_data[i, j]}")

# 6. 计算季度销售额（每3个月为一个季度）
quarterly_sales = sales_data.reshape(4, 4, 3).sum(axis=2)
print("\n季度销售额（4个季度）:")
print(quarterly_sales)


## 总结

本指南涵盖了NumPy的核心功能：

1. **数组创建**：从列表、特殊函数等多种方式创建数组
2. **数组属性**：shape、dtype、size等关键属性
3. **索引和切片**：灵活访问数组元素
4. **形状操作**：reshape、转置等操作
5. **数组操作**：拼接、分割等
6. **数学运算**：元素级和矩阵运算
7. **统计函数**：均值、方差、排序等
8. **线性代数**：矩阵运算、求解方程组等
9. **随机数生成**：各种分布的随机数
10. **实践练习**：通过实际案例巩固知识

### 进一步学习建议：
- 学习NumPy的广播机制（Broadcasting）
- 了解NumPy的内存布局和性能优化
- 学习NumPy与Pandas的配合使用
- 探索NumPy的高级索引技巧
- 学习NumPy的文件I/O操作

### 常用资源：
- NumPy官方文档：https://numpy.org/doc/
- NumPy中文文档：https://www.numpy.org.cn/
